version: '3'
services:
    cerebrum:
        image: enrichment/node_typescript:latest
        depends_on:
            - postgres
            - rhea
            - chebi
            - uniprot
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ${PWD}/opt_enrichment:/opt/enrichment:ro
            - ${PWD}/eri-cerebrum:/opt/nodeapp:rw
        environment:
            - ENRICHMENT_CONFIG=/opt/enrichment/config.json
    postgres:
        image: postgres:11-alpine
        environment: 
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=xrefdb
        volumes:
            - ${PWD}/pgdata:/var/lib/postgresql/data/pgdata
    rhea:
        image: enrichment/node:latest
        volumes:
            - ${PWD}/opt_enrichment:/opt/enrichment:ro
            - ${PWD}/eri-microservice-rhea:/opt/nodeapp:rw
        environment:
            - ENRICHMENT_CONFIG=/opt/enrichment/config.json
    chebi:
        image: enrichment/node:latest
        volumes:
            - ${PWD}/opt_enrichment:/opt/enrichment:ro
            - ${PWD}/eri-microservice-chebi:/opt/nodeapp:rw
        environment:
            - ENRICHMENT_CONFIG=/opt/enrichment/config.json
    uniprot:
        image: enrichment/node:latest
        volumes:
            - ${PWD}/opt_enrichment:/opt/enrichment:ro
            - ${PWD}/eri-microservice-uniprot:/opt/nodeapp:rw
        environment:
            - ENRICHMENT_CONFIG=/opt/enrichment/config.json

